### ISSUE TITLE
The quality of result image

### ISSUE THREAD

**Issue by khoatran02** [erman18/poison-blending-stitching#1]
Hi Erman Nghonda

First of all, I want to express my gratitude for your publicizing the source code. I am encountering an issue with the quality of the resulting image when running Poisson blending with the flower data. While the stitching and blending are satisfactory, the resulting image has a blurry layer and is not as clear as the original image. I would greatly appreciate it if you could provide me with some suggestions to resolve this issue.

![image](https://github.com/erman18/poison-blending-stitching/assets/86609606/a6c05c14-7f15-4e69-b23b-ff49e39a866c)

**Comment by ptlzon** [comment]
Hi Khoa

When I ran the code on ./data/flower folder, I got this output. I cannot see the blurry layer as in your image (but I can see the seams though). Did you modify any of the code?

![image](https://github.com/user-attachments/assets/d6dd6e6a-9472-4470-98af-0be229584f64)

**Comment by ghost** [comment]
Hi Khoa,

If you do histogram matching after that, it should be OK.

```
from skimage.exposure import match_histograms

def main_merge(img_paths: List[str], mask_paths: List[str], out_path, scf=1.) -> None:    
    # ... (keep existing code up to the poissonSolver call)
    # Convert the double image to uint8.
    img_out = convertDouble2Uint8(img_out)
    
    # Match histogram of img_out with T
    img_out_matched = match_histograms(img_out, T, multichannel=True)
        
    # Display results
    cv.imshow("Result (Before Histogram Matching)", img_out)
    cv.waitKey(0)
    cv.imshow("Result (After Histogram Matching)", img_out_matched)
    cv.waitKey(0)

# ... (keep the rest of the code)
```

![image](https://github.com/user-attachments/assets/1dbadf67-f8c4-4771-8cfa-c5abcdb4d691)

![image](https://github.com/user-attachments/assets/69dbca06-00b1-458d-b103-8e1bda4d9e17)

Is that what you want?

Best,
Lam

**Comment by khoatran02** [comment]
Dear Lam,

Thank you for your suggestion. I tried it, and it worked.

Best,
Khoa Tran
